### ISSUE TITLE
Support ES256 (feature request)

### ISSUE THREAD

**Issue by mrkvon** [nodeSolidServer/jose#18]
This algorithm is necessary to authenticate with Community Solid Server account to Node Solid Server, which uses this library and therefore [fails at that task](https://github.com/nodeSolidServer/node-solid-server/issues/1698#issuecomment-1233439791)

It seems that this library already includes placeholders for the algorithm:
https://github.com/nodeSolidServer/jose/blob/main/src/algorithms/index.js#L58
https://github.com/nodeSolidServer/jose/blob/main/src/algorithms/index.js#L113

...they just need to be filled ❤️

**Comment by dmitrizagidulin** [comment]
Yeah, that should be really easy to add

**Comment by bourgeoa** [comment]
Can you propose a PR
