### ISSUE TITLE
source contains non-free licensed RFC content

### ISSUE THREAD

**Issue by jonassmedegaard** [nodeSolidServer/jose#3]
Several files contain contents from RFC documents which are covered by licensing certainly not MIT and (by some definitions) not free:

 src/schemas/JOSEHeaderSchema.js
 src/schemas/JWECompactSerializationSchema.js
 src/schemas/JWEFlattenedSerializationSchema.js
 src/schemas/JWEJSONSerializationSchema.js
 src/schemas/JWSFlattenedSerializationSchema.js
 src/schemas/JWSJSONSerializationSchema.js
 src/schemas/JWTClaimsSetSchema.js
 test/schemas/JWKSchemaSpec.js

Please consider removing that content, to ease (re)distribution e.g. by Debian-based distributions.

See also discussion at similar issue https://github.com/anvilresearch/json-document/issues/21

**Comment by dmitrizagidulin** [comment]
Thanks @jonassmedegaard! 

We should remove the copied paragraphs (and just leave the links to those sections in the spec).

**Comment by dmitrizagidulin** [comment]
Addressed by PR #5, closing.
