### ISSUE TITLE
relies on unstable project @trust/json-document

### ISSUE THREAD

**Issue by jonassmedegaard** [nodeSolidServer/jose#4]
This project depends on https://github.com/anvilresearch/json-document which according to its authors is unfinished, unstable and likely unmaintained: https://github.com/anvilresearch/json-document/issues/21#issuecomment-530421966

**Comment by dmitrizagidulin** [comment]
@jonassmedegaard Thanks for bringing this up! I'll create a tracking issue for this, probably over at the Authentication Panel, so we can coordinate what to do about the json-document dependency in our various libs.

**Comment by dmitrizagidulin** [comment]
@jonassmedegaard So, after some discussion and research, the larger issue here is that many (and possibly all) of the libraries that use `solid/jose` will be deprecated (major bugfixes only), and replaced with [`inrupt/pod-server`](https://github.com/inrupt/pod-server).

See https://github.com/solid/node-solid-server/issues/788 for an overall discussion of how the decision to re-write the Solid software was arrived at.

Given that, I'm not sure if it's worth it to remove the dependency on json-document etc.

**Comment by jonassmedegaard** [comment]
Quoting Dmitri Zagidulin (2019-09-12 19:21:09)
> @jonassmedegaard So, after some discussion and research, the larger issue here is that many (and possibly all) of the libraries that use `solid/jose` will be deprecated (major bugfixes only), and replaced with [`inrupt/pod-server`](https://github.com/inrupt/pod-server).
> 
> See https://github.com/solid/node-solid-server/issues/788 for an overall discussion of how the decision to re-write the Solid software was arrived at.
> 
> Given that, I'm not sure if it's worth it to remove the dependency on json-document etc.

Thanks - those are valuable references!

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by dmitrizagidulin** [comment]
Addressed by PR #5, closing.
